# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
# Stage 1: Check and Install Dependencies (if needed)
- stage: DotNetSetup
  displayName: 'Check and Install Dependencies for .NET on CentOS'
  jobs:
  - job: DependencyCheck
    pool:
      name: Self-Hosted
      demands:
        - Agent.Name -equals localhost
    steps:
    - script: |
        echo "Checking for .NET SDK..."
        if ! command -v dotnet &> /dev/null; then
          echo ".NET SDK not found. Installing..."
          sudo rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
          sudo yum install -y dotnet-sdk-8.0
        else
          echo ".NET SDK already installed."
        fi

        echo "Verifying installation..."
        dotnet --info
      displayName: 'Ensure .NET SDK is Installed'

# Stage 2: Restore Dependencies
- stage: Restore
  displayName: 'Restore Dependencies'
  dependsOn: DotNetSetup
  jobs:
  - job: RestoreJob
    pool:
      name: Self-Hosted
      demands:
        - Agent.Name -equals localhost
    steps:
    - script: dotnet restore InfiniteGuide_Corner.sln
      displayName: 'Dotnet Restore'

# Stage 3: Build and Compile
- stage: Build
  displayName: 'Build and Compile'
  dependsOn: Restore
  jobs:
  - job: BuildJob
    pool:
      name: Self-Hosted
      demands:
        - Agent.Name -equals localhost
    steps:
    - script: dotnet build InfiniteGuide_Corner.sln --configuration Release
      displayName: 'Dotnet Build'