parameters:
  - name: dotnetSdkVersion
    type: string
    default: '8.0'
  - name: sonarQubeConnection
    type: string
    default: 'sonarsc'
  - name: sonarOrganization
    type: string
    default: 'ktsreddy007'
  - name: sonarProjectKey
    type: string
    default: 'ktsreddy007_ktsreddy007'
  - name: sonarProjectName
    type: string
    default: 'ktsreddy007'
  - name: acrName
    type: string
    default: 'infiacr'   

variables:
  ACR_NAME: 'infiacr'  # Replace with your ACR resource name (not login server)
  ACR_LOGIN_SERVER: 'infiacr.azurecr.io'  # Replace with your ACR login server
  RESOURCE_GROUP: 'AKSrg'
  AKS_CLUSTER_NAME: 'TejAKS'
  IMAGE_NAME: 'myapp'
  IMAGE_TAG: 'latest'    

trigger:
- main

stages:
  - stage: DotNetSetup
    displayName: 'Checks and Installs Dependencies for .NET on CentOS'
    jobs:
      - job: DependencyCheck
        pool:
          name: Self-Hosted
          demands:
            - Agent.Name -equals localhost
        steps:
          - checkout: self
            fetchDepth: 0
          - script: mkdir -p $HOME/.nuget/packages
            displayName: 'Create NuGet packages folder if missing'
          # Cache .nuget packages
          - task: Cache@2
            inputs:
              key: 'nuget | "$(Agent.OS)" | **/*.csproj, **/*.sln'
              path: $(HOME)/.nuget/packages
            displayName: 'Cache NuGet packages'

          - script: |
              echo "Checking for .NET SDK..."
              if ! command -v dotnet &> /dev/null; then
                echo ".NET SDK not found. Installing..."
                sudo rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
                sudo yum install -y dotnet-sdk-${{ parameters.dotnetSdkVersion }}
              else
                installed_version=$(dotnet --version)
                echo ".NET SDK is already installed (version: $installed_version)."
              fi
              echo "Verifying installation..."
              dotnet --info
            displayName: 'Ensure .NET SDK is Installed'

  - stage: UnitTesting
    displayName: 'Run Unit Tests'
    dependsOn: DotNetSetup
    jobs:
      - job: RunTests
        pool:
          name: Self-Hosted
          demands:
          - Agent.Name -equals localhost
        steps:
          - checkout: self
            fetchDepth: 0
          - script: mkdir -p $HOME/.nuget/packages
            displayName: 'Create NuGet packages folder if missing'
          - task: Cache@2
            inputs:
              key: 'nuget | "$(Agent.OS)" | **/*.csproj, **/*.sln'
              path: $(HOME)/.nuget/packages
            displayName: 'Cache NuGet packages'
          - script: |
              echo "Running unit tests..."
              dotnet test $(Build.SourcesDirectory)/src/Infyguide_corner/Infyguide_corner.csproj --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"
            displayName: 'Run Unit Tests'
          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'VSTest'
              testResultsFiles: '**/test_results.trx'
              failTaskOnFailedTests: true
            displayName: 'Publish Test Results'
  - stage: Sonarcloudanalysis
    displayName: 'Sonarcloud Analysis'
    dependsOn: UnitTesting
    jobs:
      - job: CodeAnalysisAndBuild
        pool:
          name: Self-Hosted
          demands:
            - Agent.Name -equals localhost
        steps:
         - task: SonarCloudPrepare@3
           inputs:
             SonarCloud: ${{ parameters.sonarQubeConnection }}
             scannerMode: 'dotnet'
             dotnetScannerVersion: '10.1.2.114627'
             projectKey: ${{ parameters.sonarProjectKey }}
             projectName: ${{ parameters.sonarProjectName }}
             organization: ${{ parameters.sonarOrganization }}

         - task: Cache@2
           inputs:
             key: 'nuget | "$(Agent.OS)" | **/*.csproj, **/*.sln'
             path: $(HOME)/.nuget/packages
           displayName: 'Cache NuGet packages'

         - script: |
             cd $(Build.SourcesDirectory)
             dotnet publish InfiniteGuide_Corner.sln --configuration Release
           displayName: 'Dotnet Build (for SonarCloud analysis)'

         - task: SonarCloudAnalyze@3
           displayName: 'Run SonarCloud Analysis'

         - task: SonarCloudPublish@3
           inputs:
             pollingTimeoutSec: '300'
           displayName: 'Publish SonarCloud Analysis Results'        

  - stage: DockerPush
    displayName: 'Push Docker Image to ACR'
    dependsOn: Sonarcloudanalysis
    jobs:
      - job: PushingToACR
        pool:
          name: Self-Hosted
          demands:
            - Agent.Name -equals localhost
        steps:
          - script: |
              echo "Building Docker image from Dockerfile..."
              docker build --cache-from ${{parameters.acrName}}.azurecr.io/myimage:latest -t myimage:latest .
            displayName: 'Build Docker Image with cache'
          - task: AzureCLI@2
            displayName: 'Login to ACR and Push Docker Image'
            inputs:
              azureSubscription: 'acrsc'  # Replace with your actual service connection name
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Logging into Azure Container Registry..."
                az acr login --name ${{parameters.acrName}}
                LOCAL_IMAGE_NAME=myimage:latest
                ACR_IMAGE_NAME=${{parameters.acrName}}.azurecr.io/myimage:latest
                echo "Tagging the local image with ACR repo..."
                docker tag $LOCAL_IMAGE_NAME $ACR_IMAGE_NAME
                echo "Pushing image to ACR..."
                docker push $ACR_IMAGE_NAME
  - stage: AKSDeployment
    displayName: 'Deploy to AKS'
    dependsOn: DockerPush
    jobs:
      - job: DeployToAKS
        pool:
          name: Self-Hosted
          demands:
            - Agent.Name -equals localhost
        steps:
          - task: AzureCLI@2
            displayName: 'Login to Azure Container Registry'
            inputs:
              azureSubscription: 'AKSsc'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                  echo "Logging into ACR..."
                  az acr login --name $(ACR_NAME)
          - task: AzureCLI@2
            displayName: 'Configure kubectl and deploy to AKS'
            inputs:
              azureSubscription: 'AKSsc'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                  echo "Setting up kubectl context for AKS..."
                  az aks get-credentials --resource-group $(RESOURCE_GROUP) --name $(AKS_CLUSTER_NAME)
                  echo "Applying Kubernetes deployment manifest..."
                  sed -i "s|REPLACE_IMAGE|$(ACR_LOGIN_SERVER)/$(IMAGE_NAME):$(IMAGE_TAG)|g" $(Build.SourcesDirectory)/deployment.yml
                  kubectl apply -f $(Build.SourcesDirectory)/deployment.yml               