trigger:
- main

stages:
  - stage: DotNetSetup
    displayName: 'Check and Install Dependencies for .NET on CentOS'
    jobs:
      - job: DependencyCheck
        pool:
          name: Self-Hosted
          demands:
            - Agent.Name -equals localhost
        steps:
          - checkout : self
            fetchDepth: 0 
          - script: |
              echo "Checking for .NET SDK..."
              if ! command -v dotnet &> /dev/null; then
                echo ".NET SDK not found. Installing..."
                echo "$sudo_user" | sudo rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
                echo "$sudo_user" | sudo yum install -y dotnet-sdk-8.0
              else
                echo ".NET SDK already installed."
              fi
              echo "Verifying installation..."
              dotnet --info
            displayName: 'Ensure .NET SDK is Installed'

  - stage: Restore
    displayName: 'Restore Dependencies'
    dependsOn: DotNetSetup
    jobs:
      - job: RestoreJob
        pool:
          name: Self-Hosted
          demands:
            - Agent.Name -equals localhost
        steps:
          - script: dotnet restore InfiniteGuide_Corner.sln
            displayName: 'Dotnet Restore'

  - stage: Build
    displayName: 'Build and Compile'
    dependsOn: Restore
    jobs:
      - job: BuildJob
        pool:
          name: Self-Hosted
          demands:
            - Agent.Name -equals localhost
        steps:
          # Step 1: Prepare SonarCloud Analysis Configuration (Now Before Build)
          - task: SonarCloudPrepare@3
            inputs:
              SonarCloud: 'sonarsc'
              scannerMode: 'dotnet'
              projectKey: 'ktsreddy007_ktsreddy007'
              projectName: 'ktsreddy007'
              organization: 'ktsreddy007'
              extraProperties: |
                sonar.branch.name=$(Build.SourceBranchName:refs/heads/)
          
          # Step 2: Clean and Build
          - script: |
              dotnet clean InfiniteGuide_Corner.sln
              dotnet build InfiniteGuide_Corner.sln --configuration Release
            displayName: 'Dotnet Clean and Build'

  - stage: SonarCloudAnalysis
    displayName: 'SonarCloud Analysis'
    dependsOn: Build
    jobs: 
      - job: SonarCloudJob
        pool:
          name: Self-Hosted
          demands:
            - Agent.Name -equals localhost
        steps:
          # Step 1: Publish the Quality Gate Result
          - task: SonarCloudPublish@3
            inputs:
              pollingTimeoutSec: '300'

  - stage: Publish
    displayName: 'Publish Application'
    dependsOn: SonarCloudAnalysis
    jobs:
      - job: PublishJob
        pool:
          name: Self-Hosted
          demands:
            - Agent.Name -equals localhost
        steps:
          - script: dotnet publish src/Infyguide_corner/Infyguide_corner.csproj -c Release -o $(pwd)/publish
            displayName: 'Dotnet Publish'