parameters:
  - name: dotnetSdkVersion
    type: string
    default: '8.0'
  - name: sonarQubeConnection
    type: string
    default: 'sonarsc'
  - name: sonarOrganization
    type: string
    default: 'ktsreddy007'
  - name: sonarProjectKey
    type: string
    default: 'ktsreddy007_ktsreddy007'
  - name: sonarProjectName
    type: string
    default: 'ktsreddy007'

trigger:
- main

stages:
  - stage: DotNetSetup
    displayName: 'Check and Install Dependencies for .NET on CentOS'
    jobs:
      - job: DependencyCheck
        pool:
          name: Self-Hosted
          demands:
            - Agent.Name -equals localhost
        steps:
          - checkout: self
            fetchDepth: 0
          - script: |
              echo "Checking for .NET SDK..."
              if ! command -v dotnet &> /dev/null; then
                echo ".NET SDK not found. Installing..."
                sudo rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
                sudo yum install -y dotnet-sdk-${{ parameters.dotnetSdkVersion }}
              else
                installed_version=$(dotnet --version)
                echo ".NET SDK is already installed (version: $installed_version)."
              fi
              echo "Verifying installation..."
              dotnet --info
            displayName: 'Ensure .NET SDK is Installed'

  - stage: Sonarcloudanalysis
    displayName: 'Sonarcloud Analysis'
    dependsOn: DotNetSetup
    jobs:
      - job: CodeAnalysisAndBuild
        pool:
          name: Self-Hosted
          demands:
            - Agent.Name -equals localhost
        steps:
         - task: SonarCloudPrepare@3
           inputs:
             SonarCloud: ${{ parameters.sonarQubeConnection }}
             scannerMode: 'dotnet'
             dotnetScannerVersion: '10.1.2.114627'
             projectKey: ${{ parameters.sonarProjectKey }}
             projectName: ${{ parameters.sonarProjectName }}
             organization: ${{ parameters.sonarOrganization }}

         - script: |
             cd $(Build.SourcesDirectory)
             dotnet build InfiniteGuide_Corner.sln --configuration Release
           displayName: 'Dotnet Build (for SonarCloud analysis)'
         - task: SonarCloudAnalyze@3
           displayName: 'Run SonarCloud Analysis'
         - task: SonarCloudPublish@3
           inputs:
             pollingTimeoutSec: '300'
           displayName: 'Publish SonarCloud Analysis Results'

  - stage: DotnetPublish
    displayName: 'Publish the .NET Application'
    dependsOn: Sonarcloudanalysis
    jobs:
      - job: PublishJob
        pool:
          name: Self-Hosted
          demands:
            - Agent.Name -equals localhost
        steps:
          - script: |
              echo "Cleaning previous builds (if any)..."
              dotnet clean InfiniteGuide_Corner.sln --configuration Release
              echo "Publishing the .NET application..."
              dotnet publish InfiniteGuide_Corner.sln --configuration Release --output $(Build.ArtifactStagingDirectory)/publish
            displayName: 'Dotnet Publish'

  - stage: Artifactoryupload
    displayName: 'Uploads Entire Publish Folder to JFrog Artifactory'
    dependsOn: DotnetPublish
    jobs:
      - job: UploadPublishFolderJob
        pool:
          name: Self-Hosted
          demands:
            - Agent.Name -equals localhost
        steps:
          - checkout: self
            fetchDepth: 0
          - task: JFrogCli@1
            displayName: 'Run JFrog CLI Command'
            inputs:
              command: 'jfrog rt ping'
              connection: 'jfrogservice'  
